In [40]:
#Importamos librer√≠as requeridas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [41]:
#Carga desde un archivo .xlsx sin indice
Credi= pd.read_excel('cuentas_credicel1.xlsx')
Credi

,folio,tag,folio_solicitud,fecha,marca,modelo,plazo,precio,enganche,descuento,...,status_cuenta,puntos,riesgo,porc_enganche,porc_tasa,score_buro,razones_buro,semana_actual,codigo_postal,Unnamed: 33
0,3,HDNAWQ3A,30,2021-11-12 19:00:05,ZTE,Blade A3 2020 RO B,26S,1949.0,780.0,0.0,...,NaN,NaN,NaN,NaN,0.00,0.0,0,0,0,NaN
1,4,M418YNR4,33,2021-11-12 19:15:58,MOTOROLA,LTE XT2097-12 E7I POWER Azul,13S,2999.0,1050.0,0.0,...,NaN,NaN,NaN,NaN,0.00,0.0,0,0,0,NaN
2,5,SZ7V3NZT,37,2021-11-13 14:13:08,ZTE,BLADE A3 2020 Gris,13S,1959.0,490.0,0.0,...,NaN,NaN,0.0,0.00,0.00,0.0,0,0,NaN,NaN
3,6,9I08UIQZ,38,2021-11-13 15:45:39,ZTE,BLADE A3 2020 Gris,13S,1959.0,490.0,0.0,...,NaN,NaN,NaN,NaN,0.00,0.0,0,0,0,NaN
4,7,JMF4LKYU,44,2021-11-13 16:10:15,MOTOROLA,G10 B,39S,4299.0,1075.0,0.0,...,Mora,0.0,0.0,0.00,0.00,0.0,NaN,NaN,74,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22730,22967,92KQVRIX,96502,2023-04-18 18:45:00,Motorola,Moto E13,26S,3349.0,297.0,0.0,...,NaN,NaN,10.0,27.40,-1.13,0.0,0,"K0,J0,D8,E2",0,NaN
22731,22968,NWB2EA8J,96479,2023-04-18 18:46:53,Motorola,Moto E22i,26S,4100.0,1209.0,0.0,...,NaN,NaN,9.0,19.00,7.48,0.0,0,"K0,J0,D8,E2",0,NaN
22732,22969,VDTRJ2W6,96442,2023-04-18 18:47:47,Samsung,A13,26S,4849.0,1152.0,0.0,...,NaN,NaN,11.0,26.65,0.75,0.0,0,"K0,D7,F7,D8",0,NaN
22733,22970,PETLF56C,96536,2023-04-18 18:49:08,Samsung,A53 5G,39S,9799.0,2799.0,0.0,...,NaN,NaN,14.0,-17.35,-0.14,0.0,0,"J0,G1,E0,E2",0,NaN
22734,22971,2CI4N2WS,96534,2023-04-18 18:49:39,Samsung,A22 5G,26S,5399.0,1086.0,0.0,...,NaN,NaN,12.0,21.80,-2.88,0.0,0,C2,0,NaN

In [42]:
valores_nulos=Credi.isnull().sum()
valores_nulos

folio                     0
tag                       0
folio_solicitud           0
fecha                     0
marca                     0
modelo                    0
plazo                     0
precio                    0
enganche                  0
descuento                 0
semana                    0
monto_financiado          0
costo_total               0
monto_accesorios          0
agente_venta              0
dis_venta                 0
status                    0
fraude                    0
empresa                  13
inversion                 0
pagos_realizados          0
reautorizacion            0
fecha_ultimo_pago      3356
fecha_pago_proximo     3356
status_cuenta          4197
puntos                 3595
riesgo                 2473
porc_enganche          2473
porc_tasa                 0
score_buro                0
razones_buro           4505
semana_actual          4505
codigo_postal           685
Unnamed: 33           22734
dtype: int64

In [43]:
Credi["empresa"]=Credi["empresa"].fillna("Desconocido")

In [44]:
valores_nulos=Credi.isnull().sum()
valores_nulos

folio                     0
tag                       0
folio_solicitud           0
fecha                     0
marca                     0
modelo                    0
plazo                     0
precio                    0
enganche                  0
descuento                 0
semana                    0
monto_financiado          0
costo_total               0
monto_accesorios          0
agente_venta              0
dis_venta                 0
status                    0
fraude                    0
empresa                   0
inversion                 0
pagos_realizados          0
reautorizacion            0
fecha_ultimo_pago      3356
fecha_pago_proximo     3356
status_cuenta          4197
puntos                 3595
riesgo                 2473
porc_enganche          2473
porc_tasa                 0
score_buro                0
razones_buro           4505
semana_actual          4505
codigo_postal           685
Unnamed: 33           22734
dtype: int64

In [45]:
Credi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22735 entries, 0 to 22734
Data columns (total 34 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   folio               22735 non-null  int64
 1   tag                 22735 non-null  object
 2   folio_solicitud     22735 non-null  int64
 3   fecha               22735 non-null  datetime64[ns]
 4   marca               22735 non-null  object
 5   modelo              22735 non-null  object
 6   plazo               22735 non-null  object
 7   precio              22735 non-null  float64
 8   enganche            22735 non-null  float64
 9   descuento           22735 non-null  float64
 10  semana              22735 non-null  int64
 11  monto_financiado    22735 non-null  float64
 12  costo_total         22735 non-null  int64
 13  monto_accesorios    22735 non-null  float64
 14  agente_venta        22735 non-null  object
 15  dis_venta           22735 non-null  object
 16  status              22735 non-null  int64
 17  fraude              22735 non-null  int64
 18  empresa             22735 non-null  object
 19  inversion           22735 non-null  int64
 20  pagos_realizados    22735 non-null  int64
 21  reautorizacion      22735 non-null  int64
 22  fecha_ultimo_pago   19379 non-null  datetime64[ns]
 23  fecha_pago_proximo  19379 non-null  datetime64[ns]
 24  status_cuenta       18538 non-null  object
 25  puntos              19140 non-null  float64
 26  riesgo              20262 non-null  float64
 27  porc_enganche       20262 non-null  float64
 28  porc_tasa           22735 non-null  float64
 29  score_buro          22735 non-null  float64
 30  razones_buro        18230 non-null  object
 31  semana_actual       18230 non-null  object
 32  codigo_postal       22050 non-null  object
 33  Unnamed: 33         1 non-null      float64
dtypes: datetime64[ns](3), float64(11), int64(9), object(11)
memory usage: 5.9+ MB

In [46]:
Credi["fecha_ultimo_pago"]=Credi["fecha_ultimo_pago"].fillna("desconocido")

In [47]:
valores_nulos=Credi.isnull().sum()
valores_nulos

folio                     0
tag                       0
folio_solicitud           0
fecha                     0
marca                     0
modelo                    0
plazo                     0
precio                    0
enganche                  0
descuento                 0
semana                    0
monto_financiado          0
costo_total               0
monto_accesorios          0
agente_venta              0
dis_venta                 0
status                    0
fraude                    0
empresa                   0
inversion                 0
pagos_realizados          0
reautorizacion            0
fecha_ultimo_pago         0
fecha_pago_proximo     3356
status_cuenta          4197
puntos                 3595
riesgo                 2473
porc_enganche          2473
porc_tasa                 0
score_buro                0
razones_buro           4505
semana_actual          4505
codigo_postal           685
Unnamed: 33           22734
dtype: int64

In [48]:
Credi["fecha_pago_proximo"]=Credi["fecha_pago_proximo"].fillna("desconocido")

In [49]:
valores_nulos=Credi.isnull().sum()
valores_nulos

folio                     0
tag                       0
folio_solicitud           0
fecha                     0
marca                     0
modelo                    0
plazo                     0
precio                    0
enganche                  0
descuento                 0
semana                    0
monto_financiado          0
costo_total               0
monto_accesorios          0
agente_venta              0
dis_venta                 0
status                    0
fraude                    0
empresa                   0
inversion                 0
pagos_realizados          0
reautorizacion            0
fecha_ultimo_pago         0
fecha_pago_proximo        0
status_cuenta          4197
puntos                 3595
riesgo                 2473
porc_enganche          2473
porc_tasa                 0
score_buro                0
razones_buro           4505
semana_actual          4505
codigo_postal           685
Unnamed: 33           22734
dtype: int64

In [50]:
Credi["status_cuenta"]=Credi["status_cuenta"].fillna("No determinado")

In [51]:
valores_nulos=Credi.isnull().sum()
valores_nulos

folio                     0
tag                       0
folio_solicitud           0
fecha                     0
marca                     0
modelo                    0
plazo                     0
precio                    0
enganche                  0
descuento                 0
semana                    0
monto_financiado          0
costo_total               0
monto_accesorios          0
agente_venta              0
dis_venta                 0
status                    0
fraude                    0
empresa                   0
inversion                 0
pagos_realizados          0
reautorizacion            0
fecha_ultimo_pago         0
fecha_pago_proximo        0
status_cuenta             0
puntos                 3595
riesgo                 2473
porc_enganche          2473
porc_tasa                 0
score_buro                0
razones_buro           4505
semana_actual          4505
codigo_postal           685
Unnamed: 33           22734
dtype: int64

In [52]:
Credi["puntos"]=Credi["puntos"].fillna(Credi["puntos"].median())

In [53]:
valores_nulos=Credi.isnull().sum()
valores_nulos

folio                     0
tag                       0
folio_solicitud           0
fecha                     0
marca                     0
modelo                    0
plazo                     0
precio                    0
enganche                  0
descuento                 0
semana                    0
monto_financiado          0
costo_total               0
monto_accesorios          0
agente_venta              0
dis_venta                 0
status                    0
fraude                    0
empresa                   0
inversion                 0
pagos_realizados          0
reautorizacion            0
fecha_ultimo_pago         0
fecha_pago_proximo        0
status_cuenta             0
puntos                    0
riesgo                 2473
porc_enganche          2473
porc_tasa                 0
score_buro                0
razones_buro           4505
semana_actual          4505
codigo_postal           685
Unnamed: 33           22734
dtype: int64

In [54]:
Credi["riesgo"]=Credi["riesgo"].fillna(Credi["riesgo"].median())

In [55]:
valores_nulos=Credi.isnull().sum()
valores_nulos

folio                     0
tag                       0
folio_solicitud           0
fecha                     0
marca                     0
modelo                    0
plazo                     0
precio                    0
enganche                  0
descuento                 0
semana                    0
monto_financiado          0
costo_total               0
monto_accesorios          0
agente_venta              0
dis_venta                 0
status                    0
fraude                    0
empresa                   0
inversion                 0
pagos_realizados          0
reautorizacion            0
fecha_ultimo_pago         0
fecha_pago_proximo        0
status_cuenta             0
puntos                    0
riesgo                    0
porc_enganche          2473
porc_tasa                 0
score_buro                0
razones_buro           4505
semana_actual          4505
codigo_postal           685
Unnamed: 33           22734
dtype: int64

In [56]:
Credi=Credi.drop('Unnamed: 33', axis=1)

In [57]:
valores_nulos=Credi.isnull().sum()
valores_nulos

folio                    0
tag                      0
folio_solicitud          0
fecha                    0
marca                    0
modelo                   0
plazo                    0
precio                   0
enganche                 0
descuento                0
semana                   0
monto_financiado         0
costo_total              0
monto_accesorios         0
agente_venta             0
dis_venta                0
status                   0
fraude                   0
empresa                  0
inversion                0
pagos_realizados         0
reautorizacion           0
fecha_ultimo_pago        0
fecha_pago_proximo       0
status_cuenta            0
puntos                   0
riesgo                   0
porc_enganche         2473
porc_tasa                0
score_buro               0
razones_buro          4505
semana_actual         4505
codigo_postal          685
dtype: int64

In [59]:
Credi["porc_enganche"]=Credi['porc_enganche'].fillna('0')

In [60]:
valores_nulos=Credi.isnull().sum()
valores_nulos

folio                    0
tag                      0
folio_solicitud          0
fecha                    0
marca                    0
modelo                   0
plazo                    0
precio                   0
enganche                 0
descuento                0
semana                   0
monto_financiado         0
costo_total              0
monto_accesorios         0
agente_venta             0
dis_venta                0
status                   0
fraude                   0
empresa                  0
inversion                0
pagos_realizados         0
reautorizacion           0
fecha_ultimo_pago        0
fecha_pago_proximo       0
status_cuenta            0
puntos                   0
riesgo                   0
porc_enganche            0
porc_tasa                0
score_buro               0
razones_buro          4505
semana_actual         4505
codigo_postal          685
dtype: int64

In [61]:
Credi['razones_buro']=Credi['razones_buro'].fillna('Desconocido')

In [62]:
Credi['semana_actual']=Credi['semana_actual'].fillna('Faltante')

In [64]:
Credi['codigo_postal']=Credi['codigo_postal'].fillna('No identificable')

In [65]:
valores_nulos=Credi.isnull().sum()
valores_nulos

folio                 0
tag                   0
folio_solicitud       0
fecha                 0
marca                 0
modelo                0
plazo                 0
precio                0
enganche              0
descuento             0
semana                0
monto_financiado      0
costo_total           0
monto_accesorios      0
agente_venta          0
dis_venta             0
status                0
fraude                0
empresa               0
inversion             0
pagos_realizados      0
reautorizacion        0
fecha_ultimo_pago     0
fecha_pago_proximo    0
status_cuenta         0
puntos                0
riesgo                0
porc_enganche         0
porc_tasa             0
score_buro            0
razones_buro          0
semana_actual         0
codigo_postal         0
dtype: int64